### ISSUE TITLE
User creating an external identifier with additional fields

### ISSUE THREAD

**Issue by philayres** [consected/restructure#307]
When an external identifier has pregenerated identifier values, as user creating a new record against a master picks from one of the currently unassigned records and adds it to the master.

When an external identifier has additional fields (additional to the external id and standard fields) and a user creates a new record against a master, any preset values in the additional fields are incorrectly overwritten. 

For example, if the external identifier has fields such as:

- redcap_link
- status

these fields may already be set by a data manager outside of the app. When the user selects to add a new external identifier, they are not really creating a new record at that point; instead the app is selecting one of the currently unassigned records. Any of the fields in that unassigned record should not be presented to the user, and none of the additional fields should overwrite the data already present in the newly assigned external identifier record.

**Comment by philayres** [comment]
To set up a test, go to the admin panel:

- Create a new external identifier with the following:
- Table name: test_invites
- Label: Test Invite
- External id attributes: test_player_id
- Category: test
- Prevent edit: checked
- Pregenerate ids: checked 
- Min: 1000
- Max: 9999
- Extra fields: link,access_code

**Pregenerate ids** and **Prevent edit** are the important flags, since it indicates that a user creating an external id is really assigning a master id from an existed pregenerated set of identifiers, rather than creating a new record, and that the identifer assigned should not be editable. The logic that handles this should be extended to prevent the additional fields overwriting existing record attributes.

When this has been created, use the User Access Controls to allow your test user to *create* *table* *test_invites*.

Then from the Details tab, select **assigned identifiers** details link. Generate more unassigned IDs, and generate 1000 ids. Then directly in the database, update all these records, setting the columns link and access_code to a non-null / non-blank value.

Now go and test as a user from the Research home page. Find or create a player record. Select the tab for *external ids* and create a new Test Invite. When you save this, the result should be that a record from the test_invites table is assigned to this user by adding a master_id to it. The desired result is that the *link* and *access_code* values are not overridden (since pregenerated and prevent edit are set in the config). Currently they are overwritten, which is incorrect.

**Comment by melonistic** [comment]
Talk to Phil before starting with this issue.
